name: Run Script

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import pathlib
            folder_path = '/home/runner/work/LTE-disdrodb-data/LTE-disdrodb-data' #os.path.join('/home/runner/work/LTE-disdrodb-data/LTE-disdrodb-data','DISDRODB','Raw')
            all_files = [os.path.join(dp, f) for dp, dn, filenames in os.walk(folder_path) for f in filenames]
            all_files_in_data_folder = [f for f in all_files if 'data' in os.path.normpath(f).split(os.sep) and os.path.basename(f) != 'url.json' ]
            if all_files_in_data_folder :
                print(all_files_in_data_folder)
                raise Exception('data file is included in the PR')